import assert from "node:assert/strict";
import { validateFormativeConversationV18R2CandidateAcceptance as validate } from "../src/lib/services/student-assessment/formative-conversation/candidate-validation-v18r2";
import { formativeConversationV18R2LifecycleForTurnCount } from "../src/lib/services/student-assessment/formative-conversation/lifecycle-contract-v18r2";
import { v18r2TestContext, v18r2TestContinueOutput, v18r2TestTerminalOutput } from "./formative-conversation-v18r2-test-fixtures";

const context = v18r2TestContext({ student_turn_count: 2 });
const partial = v18r2TestTerminalOutput({ context, outcome: "largely_improved_understanding" });
assert(partial.profile_transition_recommendation?.misconception_claim_dispositions.some(c => c.disposition === "retained"));
assert(validate({ context, candidate: partial }).valid, "Partial progress may be recorded while teaching continues");
partial.lifecycle_recommendation = "complete";
const premature = validate({ context, candidate: partial });
assert(!premature.valid);
assert(premature.validation_issue_paths.some(p => p.includes("unresolved_misconceptions")));
const noTransition = v18r2TestContinueOutput({ context });
noTransition.lifecycle_recommendation = "complete";
assert(!validate({ context, candidate: noTransition }).valid, "No transition must not drop unresolved claims");
partial.lifecycle_recommendation = "pause";
assert(validate({ context, candidate: partial }).valid, "Student pause remains available");
const sound = v18r2TestTerminalOutput({ context, outcome: "sound_understanding" });
sound.lifecycle_recommendation = "complete";
assert(validate({ context, candidate: sound }).valid, "Complete supported coverage can finish");
const unsupportedSound = structuredClone(partial);
unsupportedSound.outcome = "sound_understanding";
unsupportedSound.profile_transition_recommendation!.proposed_outcome = "sound_understanding";
assert(!validate({ context, candidate: unsupportedSound }).valid, "Sound must not retain unresolved misconceptions");
const finalContext = v18r2TestContext({ student_turn_count: 30, max_student_turns: 30 });
finalContext.formative_lifecycle = formativeConversationV18R2LifecycleForTurnCount(30, 30);
const finalPartial = v18r2TestTerminalOutput({ context: finalContext, outcome: "largely_improved_understanding" });
finalPartial.lifecycle_recommendation = "complete";
assert(validate({ context: finalContext, candidate: finalPartial }).valid, "At the limit, retain unresolved evidence without forcing mastery");
const support = v18r2TestTerminalOutput({ context, outcome: "teacher_assistance_recommended" });
support.lifecycle_recommendation = "complete";
assert(validate({ context, candidate: support }).valid, "Evidence-supported teacher support remains available");
console.log("PASS: multiple misconceptions, partial improvement, premature completion, student pause, full resolution, turn limit, teacher support");
